version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: recetas_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: recetas_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI: http://localhost:15672  guest/guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: recetas_api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=recetas_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: recetas_worker
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=recetas_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  mongo_data:
